/** Bundled demo data — used offline and as a fallback when no API key /
 *  the live call fails. Ported verbatim from the product mockup. */
import type { Draft, Op, Platform, StudioPost, Voice } from "./types";

export const DEMO: Record<Platform, Omit<Op, "_id">[]> = {
  x: [
    {
      author: "Maya Chen",
      handle: "@mayatrades",
      verified: true,
      text: "Spent 6 hours last weekend reading 10-Ks. An AI just summarized the same risk factors in 4 minutes. We are not going back.",
      likes: 18400,
      reposts: 2100,
      replies: 540,
      fit: 94,
      why_now: "High engagement and directly about AI-assisted research workflows.",
      decay_hours: 7,
      angle: "Add a concrete workflow tip",
    },
    {
      author: "Retail Investor Dad",
      handle: "@dividenddad",
      verified: false,
      text: "Honest question: how do you all actually screen 500 stocks without losing your mind? Asking for a sleep-deprived friend.",
      likes: 9200,
      reposts: 430,
      replies: 880,
      fit: 91,
      why_now: "Direct pain point your tool solves; lots of replies = visibility.",
      decay_hours: 11,
      angle: "Helpful answer, soft mention",
    },
    {
      author: "Quant Skeptic",
      handle: "@noalpha",
      verified: true,
      text: "Hot take: 90% of 'AI stock tools' are just GPT wrappers slapped on Yahoo Finance data. Prove me wrong.",
      likes: 31000,
      reposts: 4500,
      replies: 1900,
      fit: 88,
      why_now: "Spicy thread, perfect for a credible contrarian-but-respectful reply.",
      decay_hours: 5,
      angle: "Earn trust, no overclaiming",
    },
    {
      author: "FinTok Refugee",
      handle: "@chartsandvibes",
      verified: false,
      text: "The earnings season firehose is insane. By the time I read one transcript, three more dropped.",
      likes: 6400,
      reposts: 210,
      replies: 300,
      fit: 84,
      why_now: "Earnings-season timing makes this immediately relatable.",
      decay_hours: 14,
      angle: "Empathize + tip",
    },
    {
      author: "Long Term Larry",
      handle: "@compoundlarry",
      verified: true,
      text: "Reminder: the best research tool is the one you'll actually use every morning. Complexity is the enemy of consistency.",
      likes: 22000,
      reposts: 1800,
      replies: 410,
      fit: 79,
      why_now: "Aligns with a simple-daily-workflow positioning.",
      decay_hours: 20,
      angle: "Agree + extend",
    },
    {
      author: "Newbie Nina",
      handle: "@ninabuysdips",
      verified: false,
      text: "Started investing 3 months ago. Everyone says do your research but nobody says HOW. Where do I even start??",
      likes: 5100,
      reposts: 160,
      replies: 620,
      fit: 86,
      why_now: "Beginner asking exactly who your tool serves.",
      decay_hours: 16,
      angle: "Kind starter guide",
    },
  ],
  reddit: [
    {
      subreddit: "r/investing",
      author: "valuehunter88",
      title: "Is anyone actually using AI for fundamental research, or is it all hype?",
      text: "I keep seeing AI research tools advertised. Curious if anyone here uses one seriously for DD and what it actually saves you.",
      upvotes: 1240,
      comments: 430,
      fit: 93,
      why_now: "Open question inviting credible first-hand answers.",
      decay_hours: 9,
      angle: "Honest experience reply",
    },
    {
      subreddit: "r/stocks",
      author: "earnings_addict",
      title: "How do you keep up with earnings transcripts during the season?",
      text: "There are too many. I can't read them all. What's your system for not drowning in Q reports?",
      upvotes: 870,
      comments: 210,
      fit: 90,
      why_now: "Direct workflow pain your tool addresses.",
      decay_hours: 13,
      angle: "Share a system, soft mention",
    },
    {
      subreddit: "r/algotrading",
      author: "sharpe_ratio_andy",
      title: "LLMs for parsing 10-Ks — what's worked for you?",
      text: "Experimenting with feeding filings to models. Curious what pipelines people landed on and where they break.",
      upvotes: 560,
      comments: 140,
      fit: 87,
      why_now: "Technical audience, great for a substance-first reply.",
      decay_hours: 18,
      angle: "Technical value-add",
    },
    {
      subreddit: "r/SecurityAnalysis",
      author: "grahamdodd_fan",
      title: "Does AI make you a lazier analyst?",
      text: "Worried that leaning on AI summaries means I stop reading primary sources. Anyone else wrestle with this?",
      upvotes: 410,
      comments: 190,
      fit: 81,
      why_now: "Thoughtful debate where a balanced take builds authority.",
      decay_hours: 22,
      angle: "Nuanced both-sides take",
    },
    {
      subreddit: "r/investing",
      author: "firstportfolio",
      title: "Beginner overwhelmed — how to research a stock step by step?",
      text: "I have $2k and no idea how to evaluate a company. Looking for a repeatable process, not just buy index funds.",
      upvotes: 990,
      comments: 350,
      fit: 85,
      why_now: "Beginner = ideal user; high comment count.",
      decay_hours: 15,
      angle: "Step-by-step starter",
    },
    {
      subreddit: "r/stocks",
      author: "dd_or_die",
      title: "What's your pre-buy checklist?",
      text: "Trying to standardize my due diligence. What do you always check before pulling the trigger?",
      upvotes: 730,
      comments: 280,
      fit: 78,
      why_now: "Checklist threads are evergreen and shareable.",
      decay_hours: 24,
      angle: "Offer a checklist",
    },
  ],
};

export function demoDrafts(hasVoice: boolean): Draft[] {
  return [
    {
      angle: "Insightful add",
      reply:
        "This is the exact gap that killed my weekends too. What helped most wasn't speed — it was answering the same 5 risk questions for every filing so I could compare apples to apples. Consistency beats raw reading time.",
      sounds: hasVoice ? 86 : null,
      safety: "green",
      note: "Educational, no recommendations.",
    },
    {
      angle: "Friendly contrarian",
      reply:
        "Half agree. AI summaries are great for triage, but I still read primary sources on anything I'd size up. Treat it as a first-pass filter, not the final word — that's where people get burned.",
      sounds: hasVoice ? 78 : null,
      safety: "green",
      note: "Balanced, no advice.",
    },
    {
      angle: "Soft mention",
      reply:
        "Built my whole morning routine around this. Happy to share the checklist I run every company through — no pitch, just the framework that stopped me drowning in transcripts.",
      sounds: hasVoice ? 71 : null,
      safety: "amber",
      note: "Light self-promo — keep value-first to avoid spam flags.",
    },
  ];
}

export const DEMO_VOICE: Voice = {
  voice_dna:
    "Plain-spoken and a little contrarian — short punchy lines, concrete examples over jargon, and a dry humor that respects the reader's intelligence.",
  tone: "Direct, dry, credible",
  signature_moves: [
    "Opens with a sharp one-liner",
    "Uses a concrete number or example",
    "Ends on a memorable takeaway",
  ],
  vocabulary: ["honestly", "the real edge", "triage", "apples-to-apples", "do the reps"],
  avoid: ["hype words like revolutionary", "emoji spam", "vague guru-speak"],
};

export const DEMO_STUDIO: StudioPost[] = [
  {
    format: "Bold claim",
    text: "Most retail investors don't lose to the market. They lose to their own 11pm decisions made on half-read headlines. The fix isn't more information — it's a process you trust at midnight.",
    safety: "green",
    note: "Educational framing.",
  },
  {
    format: "Listicle hook",
    text: "5 questions I answer before buying any stock:\n1. What does it actually sell?\n2. Who's the customer, and do they come back?\n3. Where does the cash go?\n4. What kills the thesis?\n5. Why is it cheap (or not)?",
    safety: "green",
    note: "No specific picks.",
  },
  {
    format: "Story open",
    text: "Two years ago I spent a full Sunday reading one 10-K and felt productive. I wasn't — I was just slow. The shift: stop reading everything, start asking every filing the same questions.",
    safety: "green",
    note: "Personal, compliant.",
  },
];
